/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(triton_moving_average_cc.h) */
/* BINDTOOL_HEADER_FILE_HASH(bd0a4dcc2560685731d717b9dd54fe6c)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <torchdsp/triton_moving_average_cc.h>
// pydoc.h is automatically generated in the build directory
#include <triton_moving_average_cc_pydoc.h>

void bind_triton_moving_average_cc(py::module& m) {

    using triton_moving_average_cc = ::gr::torchdsp::triton_moving_average_cc;


    py::class_<
        triton_moving_average_cc,
        gr::sync_block,
        gr::block,
        gr::basic_block,
        std::shared_ptr<triton_moving_average_cc>>(
        m, "triton_moving_average_cc", D(triton_moving_average_cc))

        .def(
            py::init(&triton_moving_average_cc::make),
            py::arg("model_name"),
            py::arg("triton_url"),
            py::arg("tap_size"),
            D(triton_moving_average_cc, make))


        ;
}
